#!/bin/bash
#
# Container entrypoint. Idempotent: it is safe to restart the container.
#
#  1. writes cms-custom/config/settings.php from the environment
#  2. waits for the database
#  3. loads the schema on first run only
#  4. sets the admin password on first run only
#
set -euo pipefail

DB_HOST="${DB_HOST:-db}"
DB_NAME="${DB_NAME:-cms}"
DB_USER="${DB_USER:-ocm}"
DB_PASSWORD="${DB_PASSWORD:?DB_PASSWORD is not set. Copy .env.example to .env and set it.}"
BASE_URL="${BASE_URL:-/cms}"
CUSTOM_DIR=/var/www/html/cms-custom

# ── 0. Writable directories ────────────────────────────────────────────────
# cms/ is normally bind-mounted from the host, so these will not exist and will
# be owned by the host user. Create them and hand them to Apache.
for d in /var/www/html/cms/uploads /var/www/html/cms/tmp; do
	mkdir -p "$d"
	chown www-data:www-data "$d" 2>/dev/null || true
done

# ── 1. Seed the config directory, then write settings.php ──────────────────
# cms-custom is a volume so a deployment's template overrides survive a
# rebuild. On an empty volume, populate it from the copy baked into the image.
mkdir -p "$CUSTOM_DIR"
if [ -z "$(ls -A "$CUSTOM_DIR" 2>/dev/null)" ]; then
	echo "entrypoint: seeding $CUSTOM_DIR from the image"
	cp -a /opt/ocm/cms-custom-skel/. "$CUSTOM_DIR/"
fi
mkdir -p "$CUSTOM_DIR/config"

# Written every start, so changing a password in .env takes effect on restart.
cat > "$CUSTOM_DIR/config/settings.php" <<PHP
<?php
// Generated by the container entrypoint from environment variables.
// Edit .env and restart rather than editing this file; it is overwritten.
\$plSettings = array(
'db_type' => "mysql",
'db_host' => "${DB_HOST}",
'db_name' => "${DB_NAME}",
'db_user' => "${DB_USER}",
'db_password' => '${DB_PASSWORD}',
'base_url' => "${BASE_URL}",
'base_directory' => "/var/www/html/cms"
);
PHP
chown -R www-data:www-data "$CUSTOM_DIR"
chmod 600 "$CUSTOM_DIR/config/settings.php"

# ── 2. Wait for the database ───────────────────────────────────────────────
echo "entrypoint: waiting for ${DB_HOST}"
for i in $(seq 1 60); do
	if mariadb -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e 'SELECT 1' "$DB_NAME" >/dev/null 2>&1; then
		break
	fi
	if [ "$i" = 60 ]; then
		echo "entrypoint: database did not come up after 60s" >&2
		exit 1
	fi
	sleep 1
done

mysql_run() { mariadb -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" "$@"; }

# ── 3. Load the schema, first run only ─────────────────────────────────────
# `settings` is the marker table. Its presence means the schema is already
# loaded, so a restart must not reload it — that would discard real data.
if ! mysql_run -e 'SELECT 1 FROM settings LIMIT 1' >/dev/null 2>&1; then
	echo "entrypoint: empty database, loading cms/app/sql/install/new_install.sql"
	# Check the exit status. The client stops at the first failed statement
	# but the entrypoint used to ignore that and carry on, leaving a
	# half-built database that starts and then misbehaves in ways that look
	# unrelated to the real cause -- an unloaded `settings` table, for
	# instance, makes every page redirect to https.
	if ! mysql_run < /var/www/html/cms/app/sql/install/new_install.sql
	then
		echo "entrypoint: FATAL: new_install.sql failed. Refusing to start" >&2
		echo "entrypoint: the database is half-built; drop it and try again" >&2
		exit 1
	fi

	# The shipped seed forces HTTPS. That is right for a real deployment behind
	# a TLS proxy and wrong for `docker compose up` on a laptop, where it
	# redirects to a port nothing is listening on. Follow the environment.
	if [ "${FORCE_HTTPS:-0}" = "0" ]; then
		echo "entrypoint: setting force_https=0 (FORCE_HTTPS=0)"
		mysql_run -e "UPDATE settings SET value='0' WHERE label='force_https'"
	fi
	echo "entrypoint: schema loaded"
else
	echo "entrypoint: schema already present, leaving the database alone"
fi


# ── 3b. Idempotent additive upgrades ───────────────────────────────────────
# These run on EVERY start, fresh database or not, so an existing deployment
# picks up new tables by restarting the container.
#
# The list is an explicit allowlist, not `upgrades/*.sql`. The historical
# pika<version>.sql scripts in that directory are version-stepped and NOT
# idempotent — replaying pika602.sql on a 7.00 schema would fail or corrupt
# it. Only add a file here once it is safe to run repeatedly, which in
# practice means CREATE TABLE IF NOT EXISTS / ALTER ... IF NOT EXISTS only.
for upgrade in add_audit_log.sql add_csrf_tokens_table.sql add_groups_intake.sql; do
	path="/var/www/html/cms/app/sql/upgrades/${upgrade}"
	if [ ! -f "$path" ]; then
		echo "entrypoint: ${upgrade} is missing from the image" >&2
		exit 1
	fi
	if ! mysql_run < "$path"; then
		echo "entrypoint: ${upgrade} failed to apply" >&2
		exit 1
	fi
	echo "entrypoint: applied ${upgrade}"
done

# ── 4. Admin password ──────────────────────────────────────────────────────
# The shipped seed creates user_id 1 (`pikasupport`) with an empty password,
# which cannot be logged in with. Give it one.
#
# Keyed on the password being empty rather than on the schema being fresh, so a
# first start that died partway through still ends up with a usable login.
#
# The hash is written with password_hash(), the same function pikaAuthDb uses
# to verify. pl.php passes a 4th argument of 'md5' to the pikaAuthDb
# constructor, which looks like a hashing mode but is not: the constructor
# marks that parameter DEPRECATED and ignores it. Verification is
# password_verify(), with an md5 comparison kept only as a fallback that
# rewrites the row to bcrypt on the next successful login.
if [ -z "$(mysql_run -N -B -e "SELECT password FROM users WHERE user_id=1" 2>/dev/null)" ]; then
	ADMIN_USER="${ADMIN_USER:-admin}"
	ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
	generated=0
	if [ -z "$ADMIN_PASSWORD" ]; then
		# Note the read-then-filter order. `tr </dev/urandom | head -c` gives
		# tr a SIGPIPE when head has taken enough, and under `set -o pipefail`
		# that aborts the script.
		ADMIN_PASSWORD="$(head -c 200 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 20)"
		generated=1
	fi
	# Via the environment, not the argument list: a password on a command line
	# is readable in the process table.
	HASH="$(ADMIN_PASSWORD="$ADMIN_PASSWORD" php -r \
		'echo password_hash(getenv("ADMIN_PASSWORD"), PASSWORD_DEFAULT);')"
	if [ -z "$HASH" ]; then
		echo "entrypoint: password_hash produced nothing; refusing to write an empty password" >&2
		exit 1
	fi
	mysql_run -e "UPDATE users SET username='${ADMIN_USER}', password='${HASH}', group_id='system', enabled=1 WHERE user_id=1"
	if [ "$generated" = 1 ]; then
		echo "entrypoint: ================================================="
		echo "entrypoint: generated admin login"
		echo "entrypoint:   username: ${ADMIN_USER}"
		echo "entrypoint:   password: ${ADMIN_PASSWORD}"
		echo "entrypoint: Set ADMIN_PASSWORD in .env to choose your own."
		echo "entrypoint: ================================================="
	else
		echo "entrypoint: admin user is '${ADMIN_USER}', password from ADMIN_PASSWORD"
	fi
else
	echo "entrypoint: admin password already set, leaving it alone"
fi

exec "$@"
